image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  key:
    files:
      - Gemfile
      - Gemfile.lock
  paths:
    - vendor

before_script:
  - gem install bundler
  - bundle config set path 'vendor/bundle/'
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - make deploy
  artifacts:
    paths:
      - public
  only:
    - master
